### ISSUE TITLE
Error in console / Buggy items

### ISSUE THREAD

**Issue by Maingron** [Foxcapades/Spigot-Compression-Plugin#39]
I'm getting this error in my console frequently. Also the items are bugging often when using the compression table. I suspect it's the same error.

```log
[17:14:25 ERROR]: myworld-survival > Could not pass event InventoryClickEvent to block-compression v1.9.0
[17:14:25 ERROR]: myworld-survival > java.lang.IllegalStateException: Attempted to take from an empty slot.
[17:14:25 ERROR]: myworld-survival >      at io.foxcapades.spigot.block.compression.event.f.a(Unknown Source) ~[spigot-block-compression-1.9.0.jar:?]
[17:14:25 ERROR]: myworld-survival >      at io.foxcapades.spigot.block.compression.event.a.a.e.a(Unknown Source) ~[spigot-block-compression-1.9.0.jar:?]
[17:14:25 ERROR]: myworld-survival >      at io.foxcapades.spigot.block.compression.event.EventDispatch.onInventoryClick(Unknown Source) ~[spigot-block-compression-1.9.0.jar:?]
[17:14:25 ERROR]: myworld-survival >      at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[17:14:25 ERROR]: myworld-survival >      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[17:14:25 ERROR]: myworld-survival >      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3408) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1768]
[17:14:25 ERROR]: myworld-survival >      at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Maingron** [comment]
The item stays what it's supposed to be (at least I think), but it's really exhausting to work with. The GUI may reset to the previous state, for example (before you started rearranging or shifting items). I'll see if I can provide visualisation

**Comment by Foxcapades** [comment]
A visual would be perfect
